"use client";

import { Printer } from "lucide-react";

/**
 * The PDF is generated by the browser from this page, so it can never drift out
 * of date the way a checked-in file would. It also means no Playwright, no
 * build step, and no stale artefact to maintain.
 */
export function PrintButton() {
  return (
    <button
      type="button"
      onClick={() => window.print()}
      className="inline-flex items-center gap-2 rounded-full border border-border px-4 py-2 text-sm font-medium transition-colors hover:bg-muted focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none print:hidden"
    >
      <Printer className="size-4" aria-hidden />
      Save as PDF
    </button>
  );
}
